#include <iostream.h>
#include <conio.h>

void main ()
{
		clrscr ();
      cout <<  CCCCCCCC		HHH     HHH			AAAA
      cout << CCCCCCCC     HHH     HHH   	 AAA  AAA
      cout << CCC          HHH     HHH    AAA    AAA
      cout << CCC          HHHHHHHHHHH    AAA    AAA
      cout << CCC          HHH     HHH    AAAAAAAAAA
      cout << CCCCCCCC     HHH     HHH    AAA    AAA
      cout <<  CCCCCCCC    HHH     HHH    AAA    AAA